export const ROUTES = {
  HOME: "/",
  EVENT: "/event-2026",
  SPONSORS: "/sponsors",
  TICKETS: "/tickets",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  TERMESANDCONDITION: "/terms-and-conditions",
  PRIVACYPOLICY: "/privacy-policy",
  VERIFY_EMAIL: "/verify-email",
  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  PROFILE: "/profile",
  UNAUTHORIZED: "/unauthorized",
  MY_TICKET: "/my-ticket",
  ADMIN: {
    HOME: "/admin",
    LOGIN: "/admin/login",
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    TICKETS: "/admin/tickets",
    COUPONS: "/admin/coupons",
    SPONSORS: {
      HOME: "/admin/sponsors",
      CREATE: "/admin/sponsors/create",
      EDIT: (id: string) => `/admin/sponsors/edit/${id}`,
    },
    SPEAKERS: {
      HOME: "/admin/speakers",
      CREATE: "/admin/speakers/create",
      EDIT: (id: string) => `/admin/speakers/edit/${id}`,
    },
    OFFERS: "/admin/offers",
    SURVEYS: "/admin/surveys",
    GAMES: "/admin/games",
    LEADERBOARD: "/admin/leaderboard",
  },
  SPONSOR: {
    HOME: "/sponsor",
    DASHBOARD: "/sponsor/dashboard",
  },
};
