export const ROUTES = {
  HOME: "/",
  EVENT: "/event-2026",
  SPONSORS: "/sponsors",
  TICKETS: "/tickets",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  TERMESANDCONDITION: "termes-and-conditions",
  PRIVACYPOLICY: "privacy-policy",
  VERIFY_EMAIL: "/verify-email",
  UNAUTHORIZED: "/unauthorized",
  MY_TICKET: "/my-ticket",
  ADMIN: {
    HOME: "/admin",
    LOGIN: "/admin/login",
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    TICKETS: "/admin/tickets",
    COUPONS: {
      HOME: "/admin/coupons",
      CREATE: "/admin/coupons/create",
      EDIT: (id: string) => `/admin/coupons/edit/${id}`,
    },
    SPONSORS: {
      HOME: "/admin/sponsors",
      CREATE: "/admin/sponsors/create",
      EDIT: (id: string) => `/admin/sponsors/edit/${id}`,
    },
    OFFERS: {
      HOME: "/admin/offers",
      CREATE: "/admin/offers/create",
      EDIT: (id: string) => `/admin/offers/edit/${id}`,
    },
    SURVEYS: "/admin/surveys",
    GAMES: "/admin/games",
    LEADERBOARD: "/admin/leaderboard",
  },
  SPONSOR: {
    HOME: "/sponsor",
    DASHBOARD: "/sponsor/dashboard",
  },
};
