export const ROUTES = {
  HOME: "/",
  EVENT: "/event-2026",
  SPONSORS: "/sponsors",
  TICKETS: "/tickets",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  TERMESANDCONDITION: "/terms-and-conditions",
  PRIVACYPOLICY: "/privacy-policy",
  VERIFY_EMAIL: "/verify-email",
  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  PROFILE: "/profile",
  UNAUTHORIZED: "/unauthorized",
  ADMIN: {
    HOME: "/admin",
    LOGIN: "/admin/login",
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    TICKETS: "/admin/tickets",
    CHECK_IN: "/admin/check-in",
    COUPONS: {
      HOME: "/admin/coupons",
      CREATE: "/admin/coupons/create",
      EDIT: (id: string) => `/admin/coupons/edit/${id}`,
    },
    SPONSORS: {
      HOME: "/admin/sponsors",
      CREATE: "/admin/sponsors/create",
      EDIT: (id: string) => `/admin/sponsors/edit/${id}`,
    },
    SPEAKERS: {
      HOME: "/admin/speakers",
      CREATE: "/admin/speakers/create",
      EDIT: (id: string) => `/admin/speakers/edit/${id}`,
    },
    OFFERS: {
      HOME: "/admin/offers",
      CREATE: "/admin/offers/create",
      EDIT: (id: string) => `/admin/offers/edit/${id}`,
    },
    TICKET_TIERS: {
      HOME: "/admin/ticket-tiers",
      CREATE: "/admin/ticket-tiers/create",
      EDIT: (id: string) => `/admin/ticket-tiers/edit/${id}`,
    },
    PACKAGES: {
      HOME: "/admin/packages",
      CREATE: "/admin/packages/create",
      EDIT: (id: string) => `/admin/packages/edit/${id}`,
    },
    PROMO_CODES: {
      HOME: "/admin/promo-codes",
      CREATE: "/admin/promo-codes/create",
      EDIT: (id: string) => `/admin/promo-codes/edit/${id}`,
      USAGE: (id: string) => `/admin/promo-codes/usage/${id}`,
      TAGS: "/admin/promo-codes/tags",
    },
    ORDERS: {
      HOME: "/admin/orders",
      DETAILS: (id: string) => `/admin/orders/${id}`,
    },
    MANUAL_SALES: "/admin/manual-sales",
    SETTINGS: {
      HOME: "/admin/settings",
      TICKET_LIMIT: "/admin/settings/ticket-limit",
    },
    SURVEYS: "/admin/surveys",
    GAMES: "/admin/games",
    LEADERBOARD: "/admin/leaderboard",
    ACTIVITY_LOGS: "/admin/activity-logs",
  },
  SPONSOR: {
    HOME: "/sponsor",
    DASHBOARD: "/sponsor/dashboard",
  },
};
