export const mainSpeakers = [
  {
    id: "fire",
    name: "Mohamed Galal ElZeky",
    role: "The Fire",
    description: "Sales veteran & Founder of Salzkey",
    tagline:
      'Because someone needs to teach you that "no" is just a comma, not a period.',
    symbol: "🔥",
    accent: "from-[#e60000] to-[#ff6b00]",
    roleColor: "text-[#e66030]/70 group-hover:text-[#e66030]",
    image: "/images/speakers/mohamed-galal.png",
  },
  {
    id: "water",
    name: "Mohamed Ali",
    role: "The Water",
    description: "Marketer & Founder of LemonAI",
    tagline:
      "Because the future belongs to those who can surf the wave of change, not fight it.",
    symbol: "💧",
    accent: "from-[#0066cc] to-[#00aaff]",
    roleColor: "text-[#0088dd]/70 group-hover:text-[#0088dd]",
    image: "/images/speakers/mohamed-ali.png",
  },
  {
    id: "earth",
    name: "Nouran Attallah",
    role: "The Earth",
    description: "Radio/TV presenter",
    tagline: "Because sometimes the bravest thing is to be heard.",
    symbol: "✦",
    accent: "from-[#2d6a2d] to-[#5cb85c]",
    roleColor: "text-[#4a9a4a]/70 group-hover:text-[#4a9a4a]",
    image: "/images/speakers/nouran-attallah.JPG",
  },
  {
    id: "air",
    name: "Ahmed Hatem Edib",
    role: "The Air",
    description: "Marketing strategist & Co-Founder of SUTRA",
    tagline: "Because your idea deserves to be seen, not just imagined.",
    symbol: "◈",
    accent: "from-[#8844cc] to-[#bb88ff]",
    roleColor: "text-[#aa66ee]/70 group-hover:text-[#aa66ee]",
    image: "/images/speakers/ahmed-hatem.png",
  },
  {
    id: "voice",
    name: "Youssef Ali Farouk",
    role: "The Voice",
    description: "Content creator & faith-centered storyteller",
    tagline:
      "Because meaningful conversations create communities that last.",
    symbol: "♪",
    accent: "from-[#008866] to-[#00cc99]",
    roleColor: "text-[#00aa77]/70 group-hover:text-[#00aa77]",
    image: "/images/speakers/youssef-ali.png",
  },
  {
    id: "story",
    name: "Youssef Medhat",
    role: "The Storyteller",
    description: "Content creator with 333K+ followers across platforms",
    tagline:
      "Because vulnerability is the birthplace of honest connection.",
    symbol: "✦",
    accent: "from-[#cc6600] to-[#ff9933]",
    roleColor: "text-[#dd7700]/70 group-hover:text-[#dd7700]",
    image: "/images/speakers/youssef-medhat.png",
  },
];

export const keyholders = [
  {
    id: "k1",
    name: "Mohamed Alattar",
    initials: "MA",
    role: "The AI Architect",
    tagline: "Holds key to: The future of creative technology",
    image: "/images/speakers/mohamed-alattar.png",
  },
  {
    id: "k2",
    name: "Hind Mohamed",
    initials: "HM",
    role: "The Brand Alchemist",
    tagline: "Holds key to: Scientific creativity meets commercial impact",
    image: "/images/speakers/hind-mohamed.png",
  },
  {
    id: "k3",
    name: "Khaled Noureldin",
    initials: "KN",
    role: "The Community Builder",
    tagline: "Holds key to: Monetizing creativity",
    image: "/images/speakers/khaled-noureldin.png",
  },
  {
    id: "k4",
    name: "Mahmoud Allam",
    initials: "MA",
    role: "The Storyteller",
    tagline: "Holds key to: Making the complex irresistibly simple",
    image: "/images/speakers/mahmoud-allam.png",
  },
  {
    id: "k5",
    name: "Amira Elmaghraby",
    initials: "AE",
    role: "The Broadcaster",
    tagline: "Holds key to: Media narrative and public voice",
    image: "/images/speakers/amira-elmaghraby.png",
  },
  {
    id: "k6",
    name: "Mohamed Ashour",
    initials: "MA",
    role: "The Data Visionary",
    tagline: "Holds key to: Decisions driven by data, not drama",
    image: "/images/speakers/ahmed-nabil.png",
  },
  {
    id: "k7",
    name: "Captain Maged",
    initials: "CM",
    role: "The Body Philosopher",
    tagline: "Holds key to: Discipline as destiny",
    image: "/images/speakers/captain-maged.png",
  },
  {
    id: "k8",
    name: "Omar Adel",
    initials: "OA",
    role: "The PR Architect",
    tagline: "Holds key to: Communication that converts",
    image: "/images/speakers/omar-adel.png",
  },
  {
    id: "k9",
    name: "Nour El-Din Ahmed",
    initials: "NA",
    role: "The Network Weaver",
    tagline: "Holds key to: Connections that create careers",
    image: "/images/speakers/nour-eldin.png",
  },
  {
    id: "k10",
    name: "Jessica Hossam El-Din",
    initials: "JH",
    role: "The Rising Star",
    tagline: "Holds key to: Courage through artistic expression",
    image: "/images/speakers/jessica-hossam.png",
  },
  {
    id: "k11",
    name: "Anas Elbarky",
    initials: "AE",
    role: "The Mindful Guide",
    tagline: "Holds key to: Behavioral psychology & inner clarity",
    image: "/images/speakers/anas-elbarky.png",
  },
];